services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # Python news generator
  news-generator:
    image: stanleydeveloper/news-generator:latest
    build: ./news-generator
    container_name: news-generator
    depends_on:
      - rabbitmq
    environment:
    # I don't have an OpenAI API key, so please add one here if you have
      OPENAI_API_KEY: ""

  # NestJS backend
  nest-backend:
    image: stanleydeveloper/nest-backend:latest
    build: ./backend
    container_name: backend
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "3000:3000"

  # Angular frontend
  angular-frontend:
    image: stanleydeveloper/angular-frontend:latest
    build: ./frontend
    container_name: frontend
    depends_on:
      - nest-backend
    ports:
      - "8080:80"
